global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: prometheus
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: ["keycloak:9000"]

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']