package com.backend.apsor.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ApiErrorCode {
    // Auth
    INVALID_CREDENTIALS("AUTH_001"),
    EMAIL_NOT_VERIFIED("AUTH_002"),
    ACCESS_DENIED("AUTH_003"),

    // keycloak
    KEYCLOAK_ID_MISSING("AUTH_004"),
    KEYCLOAK_USER_NOT_FOUND("AUTH_005"),
    KEYCLOAK_CREDENTIAL_ERROR("AUTH_006"),
    KEYCLOAK_CONFLICT("AUTH_007"),
    KEYCLOAK_BAD_REQUEST("AUTH_008"),
    KEYCLOAK_UNAUTHORIZED("AUTH_009"),
    KEYCLOAK_FORBIDDEN("AUTH_010"),
    KEYCLOAK_ERROR("AUTH_011"),


    // User
    EMAIL_ALREADY_EXISTS("USER_001"),
    USERNAME_ALREADY_EXISTS("USER_002"),
    USER_NOT_FOUND("USER_003"),
    ROLE_NOT_FOUND("USER_004"),
    PHONE_NUMBER_ALREADY_EXISTS("USER_005"),

    // Customer
    CUSTOMER_NOT_FOUND("CUS_001"),
    CUSTOMER_ALREADY_EXISTS("CUS_002"),

    // Provider
    PROVIDER_ALREADY_EXISTS("PROV_001"),
    PROVIDER_NOT_FOUND("PROV_002"),

    // User Location
    LOCATION_NOT_FOUND("LOC_001"),
    LOCATION_ALREADY_EXISTS("LOC_002"),

    // Validation / request
    VALIDATION_ERROR("REQ_001"),
    BAD_REQUEST("REQ_002"),

    CATEGORY_NAME_EXISTS("CAT_001"),
    CATEGORY_NOT_FOUND("CAT_002"),
    CATEGORY_INACTIVE("CAT_003"),

    SUBCATEGORY_NAME_EXISTS("SUB_CAT_001"),
    SUBCATEGORY_NOT_FOUND("SUB_CAT_002"),
    SUBCATEGORY_INACTIVE("SUB_CAT_003"),

    // service
    DUPLICATE_SERVICE_RESOURCE("SERVICE_001"),
    SERVICE_NOT_FOUND("SERVICE_002"),

    // service price
    SERVICE_PRICE_NOT_FOUND("SERVICE_PRICE_001"),
    INVALID_SERVICE_PRICE("SERVICE_PRICE_002"),

    // file
    INVALID_FILE("FILE_001"),
    MEDIA_UPLOAD_FAILED("FILE_002"),
    MEDIA_ASSET_NOT_FOUND("FILE_003"),
    FILE_REQUIRED("FILE_004"),
    INVALID_FILE_NAME("FILE_005"),
    INVALID_IMAGE("INVALID_IMAGE"),
    UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
    FILE_TOO_LARGE("FILE_TOO_LARGE"),

    // Service Media
    SERVICE_MEDIA_NOT_FOUND("SERVICE_001"),

    INVALID_REQUEST("REQ_001"),

    // System
    INTERNAL_ERROR("SYS_001");

    private final String code;

}
