# .github/workflows/deploy-pages.yml
name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # 3️⃣ Upload static files
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: swagger   # folder containing index.html + static Swagger UI files

      # 4️⃣ Deploy Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
